config/routes.rb
Lyricz::Application.routes.draw do

  devise_for :admins

  resources :musicians, only: [:index, :new, :create, :show]
  resources :words, only: [:index, :new, :create, :show]

  post   '/musician_query' => 'musicians#musician_query'

  post '/words/:id/is_common_word' => 'words#is_common_word', as: 'is_common_word'

  root :to => 'musicians#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :search_count
  # has_and_belongs_to_many :words

  has_many :worduses
  has_many :words, :through => :worduses

end

app/models/musician.rb
class Musician < ActiveRecord::Base
  attr_accessible :name, :search_count

  # has_and_belongs_to_many :words

  has_many :worduses
  has_many :words, :through => :worduses

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :is_common, :search_count, :word
 
  # has_and_belongs_to_many :musicians

	has_many :worduses
  has_many :musicians, :through => :worduses

end

app/models/worduse.rb
class Worduse < ActiveRecord::Base
  attr_accessible :name, :count, :musician_id, :word_id
  
  belongs_to :musician
  belongs_to :word

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  # require 'lib/api_search'
  include ApiSearch


  def index
    @musician = Musician.new
  end

  def show
    musician = Musician.find(params[:id])
    @worduse = Worduse.where(:musician_id => musician.id)
              # Person.where(:user_name => "xyz", :status => ["active", "deleted"])
    puts @worduse
  end


  def musician_query

    # THIS IS HACKED TO AVOID BEING CHARGED MONEY
    if Musician.all.count + Worduse.all.count + Word.all.count >= 8000
      Worduse.delete_all
      Musician.delete_all
      Word.delete_all
    end


    @musician_name = params[:musician_query].downcase
    musician = Musician.find_by_name(@musician_name)

    if !musician
      musician_wordcount(@musician_name)
      words = musician_wordcount(@musician_name)
      # api stuff and save new musician
      
      musician = Musician.create(name: @musician_name)
      
      words[1].each do |key, value|

        ### line below is rails shortcut

        word = Word.find_by_word(key)
        if !word
          word = Word.create(word: key)
        end

        Worduse.create(:count => value, :musician_id => musician.id, :word_id => word.id)
      end
    end

    redirect_to musician_path(musician)

  end
end


  def api_search_musician(musician_name)

    query = musician_name
    search = MusicBrainz::Artist.find_by_name("#{query.downcase.gsub(" ", "_")}")
    return search

  end

app/controllers/words_controller.rb
class WordsController < ApplicationController


	def index
		@words = Word.all
	end
	
	def edit
  		@word = Word.find(params[:id])
	end

	def update
  		word = Word.find(params[:id])
  		word.update_attributes(params[:word])
  		word.save
  		redirect_to '/words'
	end


	def is_common_word
		word = Word.find(params[:id])
		word.toggle(:is_common)
		word.save
		redirect_to '/words'
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyricz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Sigmar+One' rel='stylesheet' type='text/css'>




</head>
<body>

<div class = "container"> 

<%= yield %>

</div>

</body>
</html>

app/views/musicians/create.html.erb
create.html.erb

app/views/musicians/index.html.erb
<div class="four columns offset-by-six alpha">
<br>
<br>
<h1>MERDS</h1>
<p><span class="small">(music words)</span></p>
<h5>Who's singing what.</h5>
<br>
<form action="/musician_query" method='post' >
	<!-- <label for="query" >Artist:</label> -->
	<input type='text' placeholder="Enter an Artist" name='musician_query' />
	<input type='submit'>
<form>

app/views/musicians/new.html.erb
<h2>MUSICIAN</h2>

<form action="/musician_query" method='post' >
	<label for="query" >Musician Name:</label>
	<input type='text' name='musician_query' />
	<input type='submit'>

<form>

app/views/musicians/show.html.erb
<div class="four columns offset-by-six alpha">
<br>
<br>
<h1>MERDS</h1>
<p><span class="small">(music words)</span></p>
<h5>Who's singing what.</h5>
<br>
<form action="/musician_query" method='post' >
	<input type='text' placeholder="<% @worduse.first(1).each do |worduse| %>
		 <%= worduse.musician.name.upcase%><% end %>" name='musician_query' />
	<input type='submit'>
<form>

<div class="clear"></div>

<div class="four columns offset-by-six alpha">

  <% word_array = [] %>

  <% @worduse.order('count DESC').take(100).each do |worduse| %>
   <%	next if worduse.word.is_common == true %>
   	<% word_array << worduse.word.word  %>		
  <% end %>

  <script>
  var fill = d3.scale.category20();

    d3.layout.cloud().size([300, 300])
        .words(["<%= raw(word_array.join('","')) %>"].map(function(d) {
          return {text: d, size: 10 + Math.random() * 90};
        }))
        .padding(5)
        .rotate(function() { return ~~(Math.random() * 2) * 90; })
        .font("Impact")
        .fontSize(function(d) { return d.size; })
        .on("end", draw)
        .start();

    function draw(words) {
      d3.select("body").append("svg")
          .attr("width", 300)
          .attr("height", 300)
        .append("g")
          .attr("transform", "translate(150,150)")
        .selectAll("text")
          .data(words)
        .enter().append("text")
          .style("font-size", function(d) { return d.size + "px"; })
          .style("font-family", "Impact")
          .style("fill", function(d, i) { return fill(i); })
          .attr("text-anchor", "middle")
          .attr("transform", function(d) {
            return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
          })
          .text(function(d) { return d.text; });
    }
  </script>
</div>

app/views/words/index.html.erb
<h1>WORDS!</h1>
<table>
	<thead>
		<tr>
			<th>Word</th>
			<th>Is Common?</th>		
		</tr>	
	</thead>
	<tbody>
		<% @words.each do |word| %>
			<tr>
				<td><%= word.word %></td>
				<td><%= word.is_common %></td>
				<td>
					<%= button_to "Is Common", is_common_word_path(word) %> 
				</td>
			</tr>	
		<% end %>
	</tbody>
</table>